# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
    param_fetcher_listener: force
#    allowed_methods_listener:  true
#    routing_loader: true
    view:
        formats:
            json: true
            rss: false
            xml: false
        view_response_listener:  true
        mime_types:
            json: ['application/json', 'application/json;version=1.0', 'application/json;version=2.0']
#    exception:
#        codes:
#            App\Exception\MyException: 403
#        messages:
#            App\Exception\MyException: Forbidden area.
    format_listener:
        rules:
            - { path: '^/', priorities: [ 'json' ], fallback_format: 'json' }
    serializer:
        serialize_null: true
    body_converter:
        enabled: true
        validate: true
        validation_errors_argument: validationErrors
    versioning:
        enabled: true
        resolvers:
            media_type: # Accept header
                enabled: true
                regex: '/(v|version)=(?P<version>[0-9\.]+)/'
